name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest 

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0

    - name: 'Build'
      run: |
        dotnet build --configuration Release

    - name: 'Publish'
      run: |
        dotnet publish src/DNQ.DataFeed.Api/DNQ.DataFeed.Api.csproj --configuration Release -o artifacts

    - uses: actions/upload-artifact@v4
      with: 
        name: artifact
        path: artifacts/