alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: app-datafeed-dev
    match:
      path:
        prefix: /
name: app-datafeed-dev
region: sgp
services:
- http_port: 8080
  image:
    deploy_on_push:
      enabled: true
    registry_type: DOCR
    repository: app-datafeed
    tag: ${{ TAG }}
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: app-datafeed-dev
