name: app-datafeed-dev
region: sgp

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - name: buildpack_stack
    value: ubuntu-22

ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: app-datafeed-dev

services:
  - name: app-datafeed-dev
    http_port: 8080
    instance_count: 2
    instance_size_slug: apps-s-1vcpu-1gb
    image:
      registry_type: DOCR
      registry: rg-app-datafeed  # Replace with your actual registry name
      repository: app-datafeed
      tag: ${TAG}
      deploy_on_push:
        enabled: true
