name: CI

on:
  push:
    branches: ["master", "DF-*-DB-MIGRATION-*", "DF-*-CI-*"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0.419-alpine3.19

    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
      LC_ALL: en_AU.UTF-8
      LANG: en_AU.UTF-8

    steps:      
      - name: 'Install dependencies'
        run: |
          #install icu-libs
          apk add --no-cache icu-libs
          dotnet tool install -g dotnet-reportgenerator-globaltool --version 5.3.11
          echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
      
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Build'
        run: |
          dotnet restore

          #test
          dotnet test --no-restore --collect:"XPlat Code Coverage"

          #build
          dotnet build src/DNQ.DataFeed.Api/DNQ.DataFeed.Api.csproj --no-restore --configuration Release
          dotnet publish src/DNQ.DataFeed.Api/DNQ.DataFeed.Api.csproj --no-build --configuration Release -o artifacts

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/

      - name: Generate test report
        run: |
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:./coverage/reports -reporttypes:Cobertura

      - name: 'Upload test report'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage/reports

      - name: 'Summary report'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: './coverage/reports/Cobertura.xml'
          badge: true
          format: markdown
          output: both

      - name: 'Add report to PR'
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  db-migration:
    if: startsWith(github.ref, 'refs/heads/DF-DB-MIGRATION-')
    name: db migration
    needs: build
    uses: ./.github/workflows/db-migration.yml
    with:
       resource_group_name: rg-datafeed-dev-mysql-central-us
       mysql_service_name: db-datafeed-dev
       env: dev
    secrets: 
       DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
       DIGITALOCEAN_MYSQL: ${{ secrets.DIGITALOCEAN_MYSQL }}

  build-docker:
    name: build docker
    runs-on: ubuntu-22.04
    needs: [build]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: app/
      
      - name: Build image
        run: docker build -t app-datafeed .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600
      
      - name: Set VERSION variable
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
        
      - name: Tag image
        run: docker tag app-datafeed registry.digitalocean.com/rg-app-datafeed/app-datafeed:${{ env.VERSION }}

      - name: Push image
        run: docker push registry.digitalocean.com/rg-app-datafeed/app-datafeed:${{ env.VERSION }}

  # deploy:
  #   name: deploy
  #   needs: build-docker
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - name: 'Deploy to App Platform'
  #       uses: digitalocean/app_action/deploy@v2
  #       env:
  #        SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
  #       with:
  #        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
