name: CI

on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0

    - name: 'Build'
      run: |
        dotnet build --configuration Release

    - name: 'Publish'
      run: |
        dotnet publish src/DNQ.DataFeed.Api/DNQ.DataFeed.Api.csproj --configuration Release -o artifacts

    - uses: actions/upload-artifact@v4
      with: 
        name: artifact
        path: artifacts/
  
  deploy_dev:
     name: Deploy dev
     needs: build
     uses: ./.github/workflows/step-deploy.yml
     with:
       env: dev
       resource_group_name: rg-datafeed-dev
       app_service_name: app-datafeed-dnquangit-dev
     secrets: 
       AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy_prod:
     name: Deploy prod
     needs: deploy_dev
     uses: ./.github/workflows/step-deploy.yml
     with:
       env: prod 
       resource_group_name: rg-datafeed-pro
       app_service_name: app-datafeed-dnquangit-prod
     secrets: 
       AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
