name: PR verify

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: PR verify
    runs-on: ubuntu-latest 

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0

    - name: 'Build'
      run: |
        dotnet build --configuration Release

    - name: 'Test'
      run: |
        dotnet test --configuration Release --no-build